function [output_file] = make_list_for_biceps(input_derivatives_directory, output_derivatives_directory, varargin)
%MAKE_LIST_FOR_BICEPS Makes a BICEPS compatible list of imaging sessions
%   Parameters
%   ----------
%   input_derivatives_directory : string
%      Path to derivatives directory that has preprocessed fMRI data
%      that you want to use with BICEPS. Data in this directory must
%      have subject folders at the top level, then optionally session
%      folders at the second level, but func at the following level.
%      Within the func folder should be at least one *.mat file and
%      one *.dtseries.nii* file that can be used to assess motion and
%      signal variability. These files must also contain the
%      rest_naming_convention term.
%   output_derivatives_directory : string
%      Path to where the BICEPS derivatives will be stored. The file list
%      generated by this function will be stored under this directory and
%      named biceps_session_list.txt
%   rest_naming_convention : optional, defaults to '*task-rest*'
%      Can be provided as the third argument. This will be added
%      to the search criteria when finding .mat and .dtseries files
%input_derivatives_directory = '/spaces/ngdr/ref-data/abcd/nda-3165-2020-09/derivatives/abcd-hcp-pipeline-v0.1.3/';

    %Save input dir
    current_dir = pwd;
    cd(input_derivatives_directory);

    %Make derivatives directory if it doesnt exist
    if isdir(output_derivatives_directory) == 0
        mkdir(output_derivatives_directory);
    end

    %Set the naming convention for task files to use in connectivity calc.
    rest_naming_convention = '*task-rest*';
    if nargin == 3
        rest_naming_convention = varargin{1};
    end

    %Be sure the rest naming convention ends in wildcard
    if strcmp(rest_naming_convention(end), '*') == 0
        rest_naming_convention = [rest_naming_convention '*'];
    end
    
    %Figure out if ses folders are around or not... pick the one with more
    %folders
    out_with_ses = dir('sub*/ses*/func/');
    out_without_ses = dir('sub*/func/');
    if (length(out_with_ses) + length(out_without_ses)) == 0
        error(['Error: No files found under ' bids_dir ' satisfying search terms sub*/ses*/func/* or sub*/func/*. Data used with BICEPS must comply with one of these two organization formats.']);
    end
    
    if length(out_with_ses) > length(out_without_ses)
        potential_biceps_folders = out_with_ses;
    else
        potential_biceps_folders = out_without_ses;
    end
    
    %Look for folders that have (1) dtseries images (for making DVARS),
    % (2) .mat files (motion stats), and (3) files matching the task
    %naming structure.
    folders_for_biceps = {};
    count = 1;
    for i = 1 : length(potential_biceps_folders)
        if potential_biceps_folders(i).isdir
            if strcmp(potential_biceps_folders(i).name, '.')
                if length(dir([potential_biceps_folders(i).folder filesep rest_naming_convention '.dtseries.nii*'])) && length(dir([potential_biceps_folders(i).folder filesep rest_naming_convention '.mat']))
                    folders_for_biceps{count} = potential_biceps_folders(i).folder(1:end-4);
                    count = count + 1;
                end
            end
        end
    end

    %Check that at least one session was found
    if length(folders_for_biceps) == 0
        disp(['WARNING: No files were found under derivatives directory ' input_derivatives_directory ' that have both *.dtseries.nii* files (for calculating DVARS) and *.mat files (for assessing motion) that also have the task specific search term ' rest_naming_convention]);
    end
    
    %Save the list of sessions to a file under the output directory.
    cd(current_dir);
    output_file = fullfile(output_derivatives_directory, 'biceps_session_list.txt');
    disp(['Output file of sessions to use with BICEPS is being saved to: ' output_file])
    fid = fopen(output_file,'w');
    fprintf(fid,'%s\n',folders_for_biceps{:});
    fclose(fid);

end